### ISSUE TITLE
Creating profile fails with an error

### ISSUE THREAD

**Issue by alexeychikk** [evald24/vscode-extensions-profiles#16]
VS Code: 1.63.2 (system setup)
OS: Windows_NT x64 10.0.19043

Creating a profile results in the following error:
```
[2021-12-24 17:43:02.254] [exthost] [error] Error: Cannot find module 'C:\Users\alexz\.vscode\extensions\\.012fa1b8-75e7-4ab1-a412-3927eed7396a\package.json'
Require stack:
- c:\Users\alexz\.vscode\extensions\evald24.vscode-extension-profiles-1.0.7\out\utils.js
- c:\Users\alexz\.vscode\extensions\evald24.vscode-extension-profiles-1.0.7\out\storage.js
- c:\Users\alexz\.vscode\extensions\evald24.vscode-extension-profiles-1.0.7\out\commands.js
- c:\Users\alexz\.vscode\extensions\evald24.vscode-extension-profiles-1.0.7\out\extension.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:32222)
    at Function.p._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:28887)
    at Function.f._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:61699)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at Module.require (c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:38461)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Users\alexz\.vscode\extensions\evald24.vscode-extension-profiles-1.0.7\out\utils.js:228:28)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\alexz\.vscode\extensions\evald24.vscode-extension-profiles-1.0.7\out\utils.js:5:58) vscode-extension-profiles.Create {"value":"evald24.vscode-extension-profiles","_lower":"evald24.vscode-extension-profiles"}
```

**Comment by evald24** [comment]
Thanks for the bug report. I'm already writing a fix.

**Comment by da-the-dev** [comment]
The `platform_slash` in `utils.ts` at 209:51 is creating problems. `extPath` is defined at line 198 and `getExtentionsPath()` returns a string with platform slash already at the end and the `platform_slash` variable I've mentioned adds an unnecessary "\\"  which causes the problem.
```ts
// Right now
let info: PackageJson = require(extPath + platform_slash + name + platform_slash + "package.json");
// Should be
let info: PackageJson = require(extPath + name + platform_slash + "package.json");
```
I'll follow up with a pull request so you can test it, I'm on Linux rn.

**Comment by da-the-dev** [comment]
> I'll follow up with a pull request so you can test it, I'm on Linux rn.

Here's the pull request: #17

**Comment by evald24** [comment]
Thank you, I noticed this and have already made corrections to version 1.0.8

**Comment by evald24** [comment]
@alexeychikk Update 1.0.8 has released, make sure that this version installed, and please check if the error has fixed

**Comment by alexeychikk** [comment]
@evald24 Now I can create and apply profiles without any issues. Thank you!
But right after I open VS Code window I get the following warnings produced by the Extension profiles:
```
Could not get information from "C:\Users\alexz\.vscode\extensions\.92667773-a909-4904-b15d-f9f6d6bd397d\package.json"
``` 
and another one
```
Could not get information from "C:\Users\alexz\.vscode\extensions\.012fa1b8-75e7-4ab1-a412-3927eed7396a\package.json"
```
Seems like it cannot access the names and descriptions of the following extensions:
`ms-vsliveshare.vsliveshare`
`yzhang.markdown-all-in-one`
because when I create or edit profiles I see template strings for these two instead of their names and descriptions.

**Comment by evald24** [comment]
@alexeychikk Yes, this is due to multilingual extensions. I'm already preparing a fix)

**Comment by evald24** [comment]
@alexeychikk Hi! Minor update 1.1.0 was released, which added support for multilingual extensions.

In order for the extension to display normally, you need to delete and re-add it.

Please give feedback =)

**Comment by alexeychikk** [comment]
@evald24 Everything is ok now, thanks!
